import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';

export interface Reservation {
  id: string;
  reservation_number: string;
  customer_name: string;
  customer_phone: string;
  customer_email: string | null;
  reservation_date: string;
  reservation_time: string;
  party_size: number;
  table_id: string | null;
  notes: string | null;
  status: string;
  created_at: string;
  updated_at: string;
}

export interface Table {
  id: string;
  name: string;
  capacity: number;
  location: string | null;
  is_active: boolean;
  sort_order: number;
}

export function useReservations() {
  const [reservations, setReservations] = useState<Reservation[]>([]);
  const [tables, setTables] = useState<Table[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchReservations = async () => {
    console.log('[useReservations] Fetching reservations...');
    const { data, error } = await supabase
      .from('reservations')
      .select('*')
      .order('reservation_date', { ascending: true })
      .order('reservation_time', { ascending: true });

    if (error) {
      console.error('[useReservations] Error fetching reservations:', error);
      return;
    }

    console.log('[useReservations] Fetched', data?.length, 'reservations');
    setReservations(data || []);
  };

  const fetchTables = async () => {
    console.log('[useReservations] Fetching tables...');
    const { data, error } = await supabase
      .from('tables')
      .select('*')
      .eq('is_active', true)
      .order('sort_order', { ascending: true });

    if (error) {
      console.error('[useReservations] Error fetching tables:', error);
      return;
    }

    console.log('[useReservations] Fetched', data?.length, 'tables');
    setTables(data || []);
  };

  useEffect(() => {
    const loadData = async () => {
      setLoading(true);
      await Promise.all([fetchReservations(), fetchTables()]);
      setLoading(false);
    };
    loadData();
  }, []);

  const addReservation = async (reservation: {
    customer_name: string;
    customer_phone: string;
    customer_email?: string | null;
    reservation_date: string;
    reservation_time: string;
    party_size: number;
    table_id?: string | null;
    notes?: string | null;
    status?: string;
  }) => {
    console.log('[useReservations] Adding reservation:', reservation);
    const { data, error } = await supabase
      .from('reservations')
      .insert([{
        ...reservation,
        reservation_number: '', // Will be auto-generated by trigger
      }])
      .select()
      .single();

    if (error) {
      console.error('[useReservations] Error adding reservation:', error);
      return null;
    }

    console.log('[useReservations] Added reservation:', data.reservation_number);
    await fetchReservations();
    return data;
  };

  const updateReservation = async (id: string, updates: Partial<Reservation>) => {
    console.log('[useReservations] Updating reservation:', id, updates);
    const { data, error } = await supabase
      .from('reservations')
      .update(updates)
      .eq('id', id)
      .select()
      .single();

    if (error) {
      console.error('[useReservations] Error updating reservation:', error);
      return null;
    }

    console.log('[useReservations] Updated reservation:', data.reservation_number);
    await fetchReservations();
    return data;
  };

  const deleteReservation = async (id: string) => {
    console.log('[useReservations] Deleting reservation:', id);
    const { error } = await supabase
      .from('reservations')
      .delete()
      .eq('id', id);

    if (error) {
      console.error('[useReservations] Error deleting reservation:', error);
      return false;
    }

    console.log('[useReservations] Deleted reservation');
    await fetchReservations();
    return true;
  };

  const updateStatus = async (id: string, status: string) => {
    return updateReservation(id, { status });
  };

  const getTableById = (tableId: string | null) => {
    if (!tableId) return null;
    return tables.find(t => t.id === tableId) || null;
  };

  return {
    reservations,
    tables,
    loading,
    addReservation,
    updateReservation,
    deleteReservation,
    updateStatus,
    getTableById,
    refetch: fetchReservations,
  };
}
